### PR TITLE
Add Progress Bar to Reader

### PR DESCRIPTION
**Pull request by michaelmckinsey1**
# Summary
Use `tqdm` to add a progress bar to the thicket reader since for larger amount of files (~1000+) in can take in the magnitude of minutes without any indication to the user (we don't want it to seem like it's hanging). The progress bar is in 2 stages for reading the files, and creating the thickets.

image

### CODE REVIEW

**Comment by michaelmckinsey1** [comment]
~Need to remove second stage and add flag to turn off tqdm by default~

**Comment by slabasan** [comment]
@michaelmckinsey1 Two things: (1) Can you take a look at the conflicting file? (2) What do you think about setting `disable_tqdm=True` in our unit tests? For one, it'll show an example of using the new parameter, and also unit tests are small enough that we don't need to be showing progress. Not sure how this will render in our static jupyter notebook outputs in RTD, but maybe we disable it there as well.

**Review by slabasan — CHANGES_REQUESTED** [review]
@michaelmckinsey1 Two things: (1) Can you take a look at the conflicting file? (2) What do you think about setting disable_tqdm=True in our unit tests? For one, it'll show an example of using the new parameter, and also unit tests are small enough that we don't need to be showing progress. Not sure how this will render in our static jupyter notebook outputs in RTD, but maybe we disable it there as well.

**Comment by michaelmckinsey1** [comment]
> @michaelmckinsey1 Two things: (1) Can you take a look at the conflicting file? (2) What do you think about setting disable_tqdm=True in our unit tests? For one, it'll show an example of using the new parameter, and also unit tests are small enough that we don't need to be showing progress. Not sure how this will render in our static jupyter notebook outputs in RTD, but maybe we disable it there as well.

1. Fixed
2. ~Would we rather have it manually set in every test that uses a reader or `concat_thickets` or done like in https://github.com/LLNL/thicket/pull/131/commits/d92a8a17e064f11fc7b2340df8565cdcd0673205~ done manually 4fea8f3

**Review by slabasan — APPROVED** [review]

**Pull request merged**
