### PR TITLE
Local Copy of NCU Python Reader

### PR DESCRIPTION
**Pull request by michaelmckinsey1**
This PR adds a copy of the Nsight Compute Python reader files such that the user is not required to have an install of Nsight Compute to use the Thicket NCU reader.

### CODE REVIEW

**Review by ilumsden — CHANGES_REQUESTED** [review]
I apparently can't reject from here, but I'm a reject for this.

This PR likely violates the terms of NVIDIA's Nsight Compute license: https://docs.nvidia.com/nsight-compute/2024.1/CopyrightAndLicenses/

**Comment by ilumsden** [comment]
Another big issue for me are the compiled libraries that are available in this PR. Currently, there are:
- `linux-desktop-glibc_2_11_3-x64`: Linux built with glibc 2.11.3 (and compatible versions) for 64-bit Intel/AMD
- `linux-desktop-glibc_2_11_3-x86`: Linux built with glibc 2.11.3 (and compatible versions) for x86 (more general than 64-bit)
- `linux-desktop-glibc_2_19_0-ppc64le`: Linux built with glibc 2.19.0 (and compatible versions) for 64-bit PowerPC
- `linux-desktop-t210-a64`: Linux built for NVIDIA Jetson (useless for us)
- `windows-desktop-win7-x64`: Windows 7 for 64-bit Intel/AMD
- `windows-desktop-win7-x86`: Windows 7 for x86

These exclude a lot of important systems:
* All macOS devices
* Linux on ARM
* Linux built with MUSL libc (e.g., Alpine Linux, some releases of Gentoo Linux)
* Windows on ARM (not super important right now, but will be in the near future with the announcement of [Qualcomm Snapdragon X and Windows Copilot+](https://www.engadget.com/microsoft-rebuilt-windows-11-around-ai-and-arm-chips-173152776.html))

And, the Windows binaries are not 100% guaranteed to work on Windows 10 or 11. There is some level of backwards compatibility, but it's very picky and finicky.

Since these are vendored into Thicket by this PR, this PR effectively limits all of Thicket to these architectures. That is a _massive_ reduction in supported platforms.

**Comment by michaelmckinsey1** [comment]
> Another big issue for me are the compiled libraries that are available in this PR. Currently, there are:
> 
> * `linux-desktop-glibc_2_11_3-x64`: Linux built with glibc 2.11.3 (and compatible versions) for 64-bit Intel/AMD
> * `linux-desktop-glibc_2_11_3-x86`: Linux built with glibc 2.11.3 (and compatible versions) for x86 (more general than 64-bit)
> * `linux-desktop-glibc_2_19_0-ppc64le`: Linux built with glibc 2.19.0 (and compatible versions) for 64-bit PowerPC
> * `linux-desktop-t210-a64`: Linux built for NVIDIA Jetson (useless for us)
> * `windows-desktop-win7-x64`: Windows 7 for 64-bit Intel/AMD
> * `windows-desktop-win7-x86`: Windows 7 for x86
> 
> These exclude a lot of important systems:
> 
> * All macOS devices
> * Linux on ARM
> * Linux built with MUSL libc (e.g., Alpine Linux, some releases of Gentoo Linux)
> * Windows on ARM (not super important right now, but will be in the near future with the announcement of [Qualcomm Snapdragon X and Windows Copilot+](https://www.engadget.com/microsoft-rebuilt-windows-11-around-ai-and-arm-chips-173152776.html))
> 
> And, the Windows binaries are not 100% guaranteed to work on Windows 10 or 11. There is some level of backwards compatibility, but it's very picky and finicky.
> 
> Since these are vendored into Thicket by this PR, this PR effectively limits all of Thicket to these architectures. That is a _massive_ reduction in supported platforms.

To be clear it would only limit the NCU reader, not the entirety of Thicket. From what I've tested, Thicket can still be used without any of the target binaries, because the [NCU exception will get handled](https://github.com/LLNL/thicket/blob/6a7904c78eef9ebee9ed706f56a2e10a1393bcf0/thicket/thicket.py#L30-L33). However, I don't know if there is a good way to collect the binaries. I have taken them from installs for testing, but this isn't efficient at all.

**Comment by michaelmckinsey1** [comment]
I'm closing this as per our discussions: keeping the NCU source in Thicket is more of a headache than it is worth.
1. It is unclear from the licensing whether this usage is permitted by NVIDIA
2. It is too difficult to manage the binaries that would be required across platforms

Below is the copyright header in the `ncu_report.py`, which seems more permissive to this application than the licensing that Ian sent. Still this licensing may only apply to `ncu_report.py`, so it's not worth the risk. I'm adding it for future reference.
```
# Copyright (c) 2020-2021, NVIDIA CORPORATION. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#  * Neither the name of NVIDIA CORPORATION nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

**Pull request closed without merging**
