### PR TITLE
Add Notebooks to Thicket Docs

### PR DESCRIPTION
**Pull request by michaelmckinsey1**
Propagate new notebooks from the Thicket tutorial to the Thicket docs.

### CODE REVIEW

**Comment by michaelmckinsey1** [comment]
~`Data type cannot be displayed: application/vnd.plotly.v1+json` error at the bottom of `tma_speedup_clustering.html` for PCP plots. It's because they are interactive.~

Fixed in 781c45e

**Comment by michaelmckinsey1** [comment]
Haven't noticed this until now, but should `tma_speedup_clustering.html` replace `thicket_rajaperf_clustering.html`?

**Comment by slabasan** [comment]
@michaelmckinsey1 Do you want to add the NCU one too? Good question on replacing `thicket_rajaperf_clustering.html`. This is reproducing figures from the HPDC paper, so I'm inclined to keep it. I realize you have improved the analysis in this notebook though.

**Comment by michaelmckinsey1** [comment]
> @michaelmckinsey1 Do you want to add the NCU one too? Good question on replacing `thicket_rajaperf_clustering.html`. This is reproducing figures from the HPDC paper, so I'm inclined to keep it. I realize you have improved the analysis in this notebook though.

I will add NCU and the parallel sorting. Maybe we should add HPDC 23 and SC 24 in the titles?

Like `Clustering RAJA Performance Suite Dataset (HPDC '23): Thicket Tutorial` and `RAJA Performance Suite Clustering Analysis (SC '24): Thicket Tutorial`

**Comment by slabasan** [comment]
I think that's a good idea, what do you think of leading with the conference? Is there a better title to differentiate the work?
* HPDC '23: Optimization-Based Clustering on RAJA Performance Suite
* P3HPC '24:  Clustering Analysis on RAJA Performance Suite
* P3HPC '24: Top Down Analysis on RAJA Performance Suite 

Wait, and don't we have two notebooks for P3HPC?

**Comment by dyokelson** [comment]
@slabasan yes, the roofline plots from P3HPC are in the ncu reader tutorial notebook, so we could point to both

(also, I agree with keeping both clustering notebooks, they are different types of clustering too)

**Comment by michaelmckinsey1** [comment]
> I think that's a good idea, what do you think of leading with the conference? Is there a better title to differentiate the work?
> 
> * HPDC '23: Optimization-Based Clustering on RAJA Performance Suite
> * P3HPC '24:  Clustering Analysis on RAJA Performance Suite
> * P3HPC '24: Top Down Analysis on RAJA Performance Suite
> 
> Wait, and don't we have two notebooks for P3HPC?

395f4f8 Updates the titles for notebooks related to published work

**Review by slabasan — APPROVED** [review]

**Pull request merged**
